stages:
  - build
  - test
  - deploy
  - install
  - present

# 1) Build every commit on every branch and add the COMMIT SHORT SHA as suffix
maven-build:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: build
  tags:
    - docker
  variables:
    DOCKER_AUTH: "$( echo -n "${CI_REGISTRY_USER}:${CI_JOB_TOKEN}" | base64 )"
    DOCKER_AUTH_CONFIG: "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"${DOCKER_AUTH}\"}}}"
  # before_script:
    # - echo "DOCKER_AUTH_CONFIG=${DOCKER_AUTH_CONFIG}"
    # - echo "$CI_REGISTRY_PASS" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    # - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - echo "DOCKER_AUTH_CONFIG=${DOCKER_AUTH_CONFIG}"
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean install -DskipTests=true
  artifacts:
    paths:
      - target
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}

# 2) Run SonarQube Tests
sonarqube-check:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: test
  tags:
    - docker
  dependencies:
    - maven-build
  variables:
    DOCKER_AUTH: 'echo -n "$CI_REGISTRY_USER:$CI_JOB_TOKEN" | base64'
    DOCKER_AUTH_CONFIG: 'echo {\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(eval $DOCKER_AUTH)\"}}}'
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn -Pcoverage verify sonar:sonar -Dsonar.host.url=https://sonar.dmx.systems -Dsonar.projectKey=${CI_PROJECT_NAMESPACE}_${CI_PROJECT_NAME}_${SONAR_PROJECT_KEY}
  allow_failure: true

# 3) Copies SNAPSHOT builds on 'main' and 'master' branch into download.dmx.systems/ci/ directory
publish-snapshot:
  stage: deploy
  tags:
    - shell
  script:
    - ci-publish.sh snapshot
  dependencies:
    - maven-build
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE != 'merge_request_event'

# 4) Copies tagged RELEASE builds into download.dmx.systems/plugins/ directory
publish-release:
  stage: deploy
  tags:
    - shell
  script:
    - ci-publish.sh release
  dependencies:
    - maven-build
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TAG != null && $CI_PIPELINE_SOURCE != 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TAG != null && $CI_PIPELINE_SOURCE != 'merge_request_event'

# 5) Deploy into gitlab maven repository
deploy-to-gitlab-maven:
  image: container-registry.dmx.systems/dmx-intern/docker-images/maven-npm-nodejs
  stage: deploy
  tags:
    - docker
  variables:
    DOCKER_AUTH: 'echo -n "$CI_REGISTRY_USER:$CI_JOB_TOKEN" | base64'
    DOCKER_AUTH_CONFIG: 'echo {\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(eval $DOCKER_AUTH)\"}}}'
  script:
    - 'mvn -Pgitlab-maven-deployment deploy -s /usr/local/lib/ci_settings.xml'
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_PIPELINE_SOURCE != 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE != 'merge_request_event'

# 6) Install in docker-container
install-in-container:
  stage: install
  tags:
    - shell-docker
  dependencies:
    - maven-build
  script:
    - ci-deploy-docker-instances.sh
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_PIPELINE_SOURCE != 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE != 'merge_request_event'

# 7) Install and reset test instance
reset-linqa-test:
  stage: present
  tags:
    - shell-docker
  when: manual
  variables:
    TIER: 'test'
  script:
    - ci-deploy-docker-instances.sh reset
  rules:
    - if: $CI_COMMIT_BRANCH == 'test' && $CI_PIPELINE_SOURCE != 'merge_request_event'

# 8) Re-install test instance without reset
persist-linqa-test:
  stage: present
  tags:
    - shell-docker
  variables:
    TIER: 'test'
  script:
    - ci-deploy-docker-instances.sh persist
  rules:
    - if: $CI_COMMIT_BRANCH == 'test' && $CI_PIPELINE_SOURCE != 'merge_request_event'
