include:
  - project: 'devops/ci-templates'
    file:
      - '/.global.yml'
      - '/.stages.yml'
      - '/.node20-maven-build.yml'
      - '/.node20-sonarqube-check.yml'
      - '/.publish.yml'
      - '/.deploy.yml'
      - '/.install.yml'
      - '/.present.yml'
      - '/.preview.yml'
