version: "3.8"


volumes:
  dmx-db:
  ldap-cfg:
  ldap-db:


services:
  dmx:
    container_name: linqa-dev-dmx-container
    restart: always
    image: container-registry.dmx.systems/dmx-contrib/dmx-docker/dmx-latest:latest
    links:
      - ldap
      - app
    environment:
      USER_ID: ${user_id}
      GROUP_ID: ${group_id}
      DMX_ADMIN_PASSWORD: ${DMX_ADMIN_PASSWORD}
      DEEPL_AUTH_KEY: ${DEEPL_AUTH_KEY}
      ## The Nextcloud user used for davfs 
      #NEXTCLOUD_USER: ${NEXTCLOUD_USER}
      #NEXTCLOUD_PASSWORD: ${NEXTCLOUD_PASSWORD}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      TIER: ${TIER}
    ## for fuse / davfs
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - dmx-db:/opt/dmx/dmx-db
      - ./dmx/zukunftswerk-dev/run.d:/opt/dmx/run.d:ro
      - ./dmx/zukunftswerk-dev/plugins:/opt/dmx/plugins:ro
      - ./dmx/zukunftswerk-dev/conf.d/config.properties.d:/opt/dmx/conf.d/config.properties.d:ro
      - ./dmx/zukunftswerk-dev/conf.d/logging.properties.d:/opt/dmx/conf.d/logging.properties.d:ro
      - /home/gitlab-runner/persist/zukunftswerk-dev/logs:/opt/dmx/logs
    #networks:
    #  zukunftswerk-dev-network:
    #    ipv4_address: 10.10.10.18

  ldap:
    container_name: linqa-dev-ldap-container
    restart: unless-stopped
    command: "--copy-service --loglevel debug"
    build:
      context: ./ldap/${TIER}
    environment:
      LDAP_ORGANISATION: "zukunftswerk"
      LDAP_DOMAIN: "zukunftswerk.org"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "bind"
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
    volumes:
      - ldap-cfg:/etc/ldap/slapd.d
      - ldap-db:/var/lib/ldap
    #networks:
    #  zukunftswerk-dev-network:
    #    ipv4_address: 10.10.10.19

  mailhog:
    container_name: linqa-dev-mailhog-container
    restart: unless-stopped
    image: container-registry.dmx.systems/dmx-intern/docker-images/mailhog:latest
    #networks:
    #  zukunftswerk-dev-network:
    #    ipv4_address: 10.10.10.20


#networks:
#  zukunftswerk-dev-network:
#    driver: bridge
#    internal: false
#    ipam:
#      config:
#        - subnet: 10.10.10.16/28
#          gateway: 10.10.10.17
